module.exports =  {
  NODE_ENV: '"production"',
  METOCLIENT_TIME_SLIDER: '"raphael"',
  METOCLIENT_SKIP_OL_FEATURE: '"true"',
  METOCLIENT_SKIP_OL_FORMAT_GEOJSON: '"true"',
  METOCLIENT_SKIP_OL_FORMAT_GML: '"true"',
  METOCLIENT_SKIP_OL_FORMAT_WFS: '"true"',
  METOCLIENT_SKIP_OL_GEOM_POINT: '"true"',
  METOCLIENT_SKIP_OL_LAYER_VECTOR: '"true"',
  METOCLIENT_SKIP_OL_SOURCE_OSM: '"true"',
  METOCLIENT_SKIP_OL_SOURCE_STAMEN: '"true"',
  METOCLIENT_SKIP_OL_SOURCE_VECTOR: '"true"',
  METOCLIENT_SKIP_OL_STYLE_FILL: '"true"',
  METOCLIENT_SKIP_OL_STYLE_ICON: '"true"',
  METOCLIENT_SKIP_OL_STYLE_STROKE: '"true"',
  METOCLIENT_SKIP_OL_STYLE_STYLE: '"true"',
  METOCLIENT_SKIP_OL_STYLE_TEXT: '"true"'
}
